// ============================================================
// LanguageContext.jsx — Global Language State
//
// Stores the selected language across the entire app
// Any component can read or change the language using useLanguage()
// Language is saved in localStorage so it persists after refresh
// ============================================================

import React, { createContext, useContext, useState } from "react";
import customTranslations from "../translations/translations";

// ── All translations live here ────────────────────────────────
// To add a new language → add a new key with all the same fields
export const translations = {

  // ── ENGLISH ───────────────────────────────────────────────
  en: {
    // Language selector
    selectLanguage: "Select Language",
    languageName: "English",

    // Navbar
    nav_home: "Home",
    nav_dashboard: "Dashboard",
    nav_advisories: "Advisories ▾",
    nav_crop: "🌾 Crop Recommendation",
    nav_fertilizer: "💊 Fertilizer",
    nav_irrigation: "💧 Irrigation",
    nav_disease: "🦠 Disease Detection",
    nav_profile: "My Profile",
    nav_logout: "Logout",
    nav_login: "Login",
    nav_register: "Register",

    // Home Page
    home_badge: "🌿 AI-Powered Agriculture",
    home_title1: "Smart Farming Starts",
    home_title2: "With Smart Data",
    home_desc: "Get AI-generated, personalized recommendations for crops, fertilizers, irrigation, and disease detection — all based on your real field conditions.",
    home_getStarted: "🌱 Get Started Free",
    home_login: "🔑 Login",
    home_dashboard: "🌾 Go to Dashboard",
    home_stat1: "Crop Model Accuracy",
    home_stat2: "Crops Supported",
    home_stat3: "AI Models",
    home_whatWeOffer: "What We Offer",
    home_whatDesc: "Four intelligent advisory services powered by trained Machine Learning models",
    home_howItWorks: "How It Works",
    home_howDesc: "Four simple steps from soil data to actionable recommendations",
    home_builtWith: "Built With Modern Technology",
    home_builtDesc: "A three-tier full-stack architecture — frontend, backend, and AI",
    home_readyTitle: "Ready to Farm Smarter?",
    home_readyDesc: "Create your free account and get your first recommendation in minutes.",
    home_startNow: "🌱 Start Now — It's Free",

    // Features
    feat1_title: "Crop Recommendation",
    feat1_desc: "Enter your soil NPK values, temperature, humidity, pH, and rainfall to get the best crop recommendation.",
    feat2_title: "Fertilizer Advisory",
    feat2_desc: "Get personalized fertilizer recommendations based on your crop choice and soil nutrient levels.",
    feat3_title: "Irrigation Guidance",
    feat3_desc: "Know exactly how much water your crop needs and how frequently to irrigate.",
    feat4_title: "Disease Detection",
    feat4_desc: "Describe visible symptoms and get instant disease identification with treatment guidance.",

    // Steps
    step1_title: "Enter Field Data",
    step1_desc: "Input your soil values and local climate conditions.",
    step2_title: "AI Analysis",
    step2_desc: "Our ML models analyze your data in real time.",
    step3_title: "Get Recommendation",
    step3_desc: "Receive personalized, actionable agricultural advice.",
    step4_title: "Track Your History",
    step4_desc: "All recommendations are saved for future reference.",

    // Login Page
    login_welcome: "Welcome Back",
    login_subtitle: "Sign in to your Smart Crop Advisor account",
    login_email: "Email Address",
    login_password: "Password",
    login_submit: "🔑 Sign In",
    login_loading: "Signing in...",
    login_noAccount: "Don't have an account?",
    login_createOne: "Create one here",
    login_error_empty: "Please fill in both email and password.",

    // Register Page
    register_title: "Create Account",
    register_subtitle: "Join Smart Crop Advisor and farm smarter today",
    register_name: "Full Name",
    register_email: "Email Address",
    register_location: "Location / Village",
    register_password: "Password",
    register_confirmPassword: "Confirm Password",
    register_submit: "🌱 Create My Account",
    register_loading: "Creating account...",
    register_haveAccount: "Already have an account?",
    register_signIn: "Sign in here",
    register_success: "Account created! Redirecting to login...",
    register_error_empty: "All fields are required.",
    register_error_password: "Passwords do not match.",
    register_error_short: "Password must be at least 6 characters.",

    // Dashboard
    dash_welcome: "Welcome back,",
    dash_subtitle: "Here's your agricultural advisory summary and recent activity.",
    dash_profile: "👨‍🌾 My Profile",
    dash_totalAdvisories: "Total Advisories",
    dash_cropRec: "Crop Recommendations",
    dash_fertAdvisory: "Fertilizer Advisories",
    dash_lastDate: "Last Advisory Date",
    dash_quickActions: "Quick Actions",
    dash_recentRec: "Recent Recommendations",
    dash_noHistory: "No recommendations yet.",
    dash_noHistoryDesc: "Try the Crop Recommendation feature to get started!",
    dash_getFirst: "Get First Recommendation",
    dash_loading: "Loading your history...",
    dash_col_type: "Type",
    dash_col_result: "Result",
    dash_col_confidence: "Confidence",
    dash_col_date: "Date",

    // Crop Recommend
    crop_title: "🌾 Crop Recommendation",
    crop_subtitle: "Enter your soil and climate data. Our AI model will recommend the best crop for your field.",
    crop_formTitle: "📋 Enter Field Data",
    crop_formSubtitle: "All values must reflect your current field conditions.",
    crop_nitrogen: "Nitrogen (N)",
    crop_phosphorus: "Phosphorus (P)",
    crop_potassium: "Potassium (K)",
    crop_temperature: "Temperature",
    crop_humidity: "Humidity",
    crop_ph: "Soil pH",
    crop_rainfall: "Rainfall",
    crop_submit: "🤖 Get Recommendation",
    crop_loading: "Analyzing...",
    crop_reset: "🔄 Reset",
    crop_resultTitle: "Your recommendation will appear here",
    crop_resultDesc: "Fill in the form and click Get Recommendation",
    crop_success: "Recommendation generated and saved!",
    crop_error_empty: "Please fill in all the fields before submitting.",
    crop_tip_n: "Available nitrogen in soil. Ideal: 0–140 mg/kg",
    crop_tip_p: "Available phosphorus in soil. Ideal: 5–145 mg/kg",
    crop_tip_k: "Available potassium in soil. Ideal: 5–205 mg/kg",
    crop_tip_temp: "Average local temperature. Ideal: 10–45 °C",
    crop_tip_humidity: "Relative humidity in the field. Range: 14–100 %",
    crop_tip_ph: "Soil acidity/alkalinity. Neutral is 7. Range: 3.5–10",
    crop_tip_rainfall: "Annual or seasonal rainfall. Range: 20–300 mm",

    // Recommendation Card
    card_cropLabel: "Crop Recommendation",
    card_fertLabel: "Fertilizer Recommendation",
    card_irrigLabel: "Irrigation Advisory",
    card_diseaseLabel: "Disease Detection Result",
    card_confidence: "Confidence",
    card_alternatives: "Alternatives:",
    card_advisory: "📋 Advisory Note",
    card_prevention: "🛡️ Prevention",
    card_quantity: "Quantity:",
    card_frequency: "Frequency:",
    card_method: "Method:",
    card_severity: "Severity",

    // Fertilizer
    fert_title: "💊 Fertilizer Recommendation",
    fert_subtitle: "Select your crop and soil type, enter NPK levels to get a personalized fertilizer recommendation.",
    fert_formTitle: "📋 Enter Details",
    fert_cropName: "Crop Name",
    fert_soilType: "Soil Type",
    fert_selectCrop: "-- Select your crop --",
    fert_selectSoil: "-- Select soil type --",
    fert_nitrogen: "Nitrogen (N)",
    fert_phosphorus: "Phosphorus (P)",
    fert_potassium: "Potassium (K)",
    fert_submit: "💊 Get Fertilizer Advice",
    fert_loading: "Analyzing...",
    fert_reset: "🔄 Reset",
    fert_resultTitle: "Your fertilizer advice will appear here",
    fert_resultDesc: "Select crop, soil type, and enter NPK values to proceed",
    fert_success: "Fertilizer recommendation saved!",
    fert_error_empty: "Please fill in all fields.",

    // Irrigation
    irrig_title: "💧 Irrigation Advisory",
    irrig_subtitle: "Tell us your crop type, soil moisture, temperature, and growth stage for the optimal water plan.",
    irrig_formTitle: "📋 Field Conditions",
    irrig_cropName: "Crop Name",
    irrig_growthStage: "Growth Stage",
    irrig_soilMoisture: "Soil Moisture",
    irrig_temperature: "Temperature",
    irrig_selectCrop: "-- Select crop --",
    irrig_selectStage: "-- Select growth stage --",
    irrig_submit: "💧 Get Irrigation Plan",
    irrig_loading: "Calculating...",
    irrig_reset: "🔄 Reset",
    irrig_resultTitle: "Your irrigation plan will appear here",
    irrig_resultDesc: "Select your crop and enter field conditions to get a plan",
    irrig_success: "Irrigation plan generated and saved!",
    irrig_error_empty: "Please fill in all fields.",
    irrig_tip_moisture: "Current moisture level of your soil (0–100%)",
    irrig_tip_temp: "Current daytime temperature in your field",

    // Disease
    disease_title: "🦠 Disease Detection",
    disease_subtitle: "Select your crop and describe symptoms. Our AI will identify the likely disease and suggest treatment.",
    disease_formTitle: "📋 Describe the Problem",
    disease_cropLabel: "Affected Crop",
    disease_selectCrop: "-- Select affected crop --",
    disease_symptomsLabel: "Observed Symptoms",
    disease_symptomsHint: "Select all symptoms you can see on the plant:",
    disease_customLabel: "Additional Symptom Description (Optional)",
    disease_customPlaceholder: "e.g. leaves turning brittle and falling early",
    disease_selectedCount: "symptom(s) selected",
    disease_submit: "🔬 Detect Disease",
    disease_loading: "Detecting...",
    disease_reset: "🔄 Reset",
    disease_resultTitle: "Disease detection result will appear here",
    disease_resultDesc: "Select your crop and at least one symptom to proceed",
    disease_success: "Disease detected. Result saved to history.",
    disease_supportedTitle: "📋 Supported Diseases",
    disease_supportedDesc: "Our system can identify these diseases:",
    disease_error_noCrop: "Please select your crop first.",
    disease_error_noSymptom: "Please select or describe at least one symptom.",
    // Symptoms
    sym1: "Yellow leaves",
    sym2: "Brown spots on leaves",
    sym3: "Wilting stems",
    sym4: "White powder on leaves",
    sym5: "Black lesions",
    sym6: "Stunted growth",
    sym7: "Root rot",
    sym8: "Leaf curl",
    sym9: "Fruit discoloration",
    sym10: "Premature fruit drop",
    sym11: "Water-soaked patches",
    sym12: "Rusty orange pustules",

    // Profile
    profile_title: "👨‍🌾 My Profile",
    profile_subtitle: "Manage your account information",
    profile_loading: "Loading your profile...",
    profile_location: "📍 Location",
    profile_member: "📅 Member since",
    profile_notSet: "Not set",
    profile_editTitle: "Edit Information",
    profile_editBtn: "✏️ Edit Profile",
    profile_name: "Full Name",
    profile_email: "Email Address",
    profile_emailNote: "Email address cannot be changed after registration.",
    profile_locationLabel: "Location / Village",
    profile_save: "💾 Save Changes",
    profile_saving: "Saving...",
    profile_cancel: "Cancel",
    profile_dangerTitle: "⚠️ Danger Zone",
    profile_dangerDesc: "Deleting your account is permanent. All your recommendations and data will be permanently removed.",
    profile_deleteBtn: "🗑️ Delete My Account",
    profile_deleting: "Deleting...",
    profile_success: "Profile updated successfully!",
    profile_error_name: "Name cannot be empty.",
    profile_confirmDelete: "Are you absolutely sure you want to delete your account?\n\nAll your recommendations and data will be permanently deleted.",

    // Alert / Loader
    loading_ai: "AI is analyzing your field data...",
    loading_disease: "AI is analyzing symptoms...",
    loading_fertilizer: "Calculating fertilizer recommendation...",
    loading_irrigation: "Calculating your irrigation plan...",
    loading_history: "Loading your history...",
  },

  // ── HINDI ─────────────────────────────────────────────────
  hi: {
    selectLanguage: "भाषा चुनें",
    languageName: "हिंदी",

    nav_home: "होम",
    nav_dashboard: "डैशबोर्ड",
    nav_advisories: "सलाह ▾",
    nav_crop: "🌾 फसल सिफारिश",
    nav_fertilizer: "💊 उर्वरक",
    nav_irrigation: "💧 सिंचाई",
    nav_disease: "🦠 रोग पहचान",
    nav_profile: "मेरी प्रोफाइल",
    nav_logout: "लॉग आउट",
    nav_login: "लॉग इन",
    nav_register: "पंजीकरण",

    home_badge: "🌿 AI-संचालित कृषि",
    home_title1: "स्मार्ट खेती की शुरुआत",
    home_title2: "स्मार्ट डेटा से होती है",
    home_desc: "अपनी वास्तविक खेत की स्थिति के आधार पर फसल, उर्वरक, सिंचाई और रोग पहचान के लिए AI-आधारित व्यक्तिगत सिफारिशें पाएं।",
    home_getStarted: "🌱 मुफ्त शुरू करें",
    home_login: "🔑 लॉग इन",
    home_dashboard: "🌾 डैशबोर्ड पर जाएं",
    home_stat1: "फसल मॉडल सटीकता",
    home_stat2: "समर्थित फसलें",
    home_stat3: "AI मॉडल",
    home_whatWeOffer: "हम क्या प्रदान करते हैं",
    home_whatDesc: "प्रशिक्षित मशीन लर्निंग मॉडल द्वारा संचालित चार बुद्धिमान सलाह सेवाएं",
    home_howItWorks: "यह कैसे काम करता है",
    home_howDesc: "मिट्टी डेटा से व्यावहारिक सिफारिशों तक चार सरल चरण",
    home_builtWith: "आधुनिक तकनीक से निर्मित",
    home_builtDesc: "तीन-स्तरीय पूर्ण-स्टैक आर्किटेक्चर",
    home_readyTitle: "स्मार्ट तरीके से खेती करने के लिए तैयार हैं?",
    home_readyDesc: "अपना मुफ्त खाता बनाएं और मिनटों में पहली सिफारिश पाएं।",
    home_startNow: "🌱 अभी शुरू करें — यह मुफ्त है",

    feat1_title: "फसल सिफारिश",
    feat1_desc: "मिट्टी के NPK मान, तापमान, आर्द्रता, pH और वर्षा दर्ज करें और सर्वोत्तम फसल की सिफारिश पाएं।",
    feat2_title: "उर्वरक सलाह",
    feat2_desc: "अपनी फसल और मिट्टी के पोषक तत्वों के आधार पर व्यक्तिगत उर्वरक सिफारिश पाएं।",
    feat3_title: "सिंचाई मार्गदर्शन",
    feat3_desc: "जानें कि आपकी फसल को कितने पानी की जरूरत है और कितनी बार सिंचाई करनी है।",
    feat4_title: "रोग पहचान",
    feat4_desc: "दृश्य लक्षण बताएं और तत्काल रोग पहचान एवं उपचार मार्गदर्शन पाएं।",

    step1_title: "खेत का डेटा दर्ज करें",
    step1_desc: "अपनी मिट्टी के मान और स्थानीय जलवायु की जानकारी दर्ज करें।",
    step2_title: "AI विश्लेषण",
    step2_desc: "हमारे ML मॉडल आपके डेटा का वास्तविक समय में विश्लेषण करते हैं।",
    step3_title: "सिफारिश पाएं",
    step3_desc: "व्यक्तिगत, व्यावहारिक कृषि सलाह प्राप्त करें।",
    step4_title: "इतिहास देखें",
    step4_desc: "सभी सिफारिशें भविष्य के संदर्भ के लिए सहेजी जाती हैं।",

    login_welcome: "वापस स्वागत है",
    login_subtitle: "अपने स्मार्ट क्रॉप एडवाइजर खाते में साइन इन करें",
    login_email: "ईमेल पता",
    login_password: "पासवर्ड",
    login_submit: "🔑 साइन इन करें",
    login_loading: "साइन इन हो रहा है...",
    login_noAccount: "खाता नहीं है?",
    login_createOne: "यहाँ बनाएं",
    login_error_empty: "कृपया ईमेल और पासवर्ड दोनों भरें।",

    register_title: "खाता बनाएं",
    register_subtitle: "स्मार्ट क्रॉप एडवाइजर से जुड़ें और स्मार्ट तरीके से खेती करें",
    register_name: "पूरा नाम",
    register_email: "ईमेल पता",
    register_location: "स्थान / गाँव",
    register_password: "पासवर्ड",
    register_confirmPassword: "पासवर्ड की पुष्टि करें",
    register_submit: "🌱 मेरा खाता बनाएं",
    register_loading: "खाता बन रहा है...",
    register_haveAccount: "पहले से खाता है?",
    register_signIn: "यहाँ साइन इन करें",
    register_success: "खाता बन गया! लॉगिन पर जा रहे हैं...",
    register_error_empty: "सभी फ़ील्ड आवश्यक हैं।",
    register_error_password: "पासवर्ड मेल नहीं खाते।",
    register_error_short: "पासवर्ड कम से कम 6 अक्षर का होना चाहिए।",

    dash_welcome: "वापस स्वागत है,",
    dash_subtitle: "यहाँ आपका कृषि सलाह सारांश और हालिया गतिविधि है।",
    dash_profile: "👨‍🌾 मेरी प्रोफाइल",
    dash_totalAdvisories: "कुल सलाहें",
    dash_cropRec: "फसल सिफारिशें",
    dash_fertAdvisory: "उर्वरक सलाहें",
    dash_lastDate: "अंतिम सलाह तिथि",
    dash_quickActions: "त्वरित क्रियाएं",
    dash_recentRec: "हालिया सिफारिशें",
    dash_noHistory: "अभी तक कोई सिफारिश नहीं।",
    dash_noHistoryDesc: "शुरू करने के लिए फसल सिफारिश सुविधा आज़माएं!",
    dash_getFirst: "पहली सिफारिश पाएं",
    dash_loading: "आपका इतिहास लोड हो रहा है...",
    dash_col_type: "प्रकार",
    dash_col_result: "परिणाम",
    dash_col_confidence: "विश्वास",
    dash_col_date: "तिथि",

    crop_title: "🌾 फसल सिफारिश",
    crop_subtitle: "अपनी मिट्टी और जलवायु डेटा दर्ज करें। हमारा AI मॉडल आपके खेत के लिए सबसे अच्छी फसल की सिफारिश करेगा।",
    crop_formTitle: "📋 खेत का डेटा दर्ज करें",
    crop_formSubtitle: "सभी मान आपकी वर्तमान खेत की स्थिति को दर्शाने चाहिए।",
    crop_nitrogen: "नाइट्रोजन (N)",
    crop_phosphorus: "फास्फोरस (P)",
    crop_potassium: "पोटेशियम (K)",
    crop_temperature: "तापमान",
    crop_humidity: "आर्द्रता",
    crop_ph: "मिट्टी का pH",
    crop_rainfall: "वर्षा",
    crop_submit: "🤖 सिफारिश पाएं",
    crop_loading: "विश्लेषण हो रहा है...",
    crop_reset: "🔄 रीसेट",
    crop_resultTitle: "आपकी सिफारिश यहाँ दिखेगी",
    crop_resultDesc: "फॉर्म भरें और सिफारिश पाएं बटन दबाएं",
    crop_success: "सिफारिश तैयार हो गई और सहेज ली गई!",
    crop_error_empty: "कृपया सबमिट करने से पहले सभी फ़ील्ड भरें।",
    crop_tip_n: "मिट्टी में उपलब्ध नाइट्रोजन। आदर्श: 0–140 mg/kg",
    crop_tip_p: "मिट्टी में उपलब्ध फास्फोरस। आदर्श: 5–145 mg/kg",
    crop_tip_k: "मिट्टी में उपलब्ध पोटेशियम। आदर्श: 5–205 mg/kg",
    crop_tip_temp: "औसत स्थानीय तापमान। आदर्श: 10–45 °C",
    crop_tip_humidity: "खेत में सापेक्ष आर्द्रता। सीमा: 14–100 %",
    crop_tip_ph: "मिट्टी की अम्लता/क्षारीयता। तटस्थ 7 है। सीमा: 3.5–10",
    crop_tip_rainfall: "वार्षिक या मौसमी वर्षा। सीमा: 20–300 mm",

    card_cropLabel: "फसल सिफारिश",
    card_fertLabel: "उर्वरक सिफारिश",
    card_irrigLabel: "सिंचाई सलाह",
    card_diseaseLabel: "रोग पहचान परिणाम",
    card_confidence: "विश्वास",
    card_alternatives: "विकल्प:",
    card_advisory: "📋 सलाह नोट",
    card_prevention: "🛡️ रोकथाम",
    card_quantity: "मात्रा:",
    card_frequency: "आवृत्ति:",
    card_method: "विधि:",
    card_severity: "गंभीरता",

    fert_title: "💊 उर्वरक सिफारिश",
    fert_subtitle: "अपनी फसल और मिट्टी का प्रकार चुनें, NPK स्तर दर्ज करें।",
    fert_formTitle: "📋 विवरण दर्ज करें",
    fert_cropName: "फसल का नाम",
    fert_soilType: "मिट्टी का प्रकार",
    fert_selectCrop: "-- अपनी फसल चुनें --",
    fert_selectSoil: "-- मिट्टी का प्रकार चुनें --",
    fert_nitrogen: "नाइट्रोजन (N)",
    fert_phosphorus: "फास्फोरस (P)",
    fert_potassium: "पोटेशियम (K)",
    fert_submit: "💊 उर्वरक सलाह पाएं",
    fert_loading: "विश्लेषण हो रहा है...",
    fert_reset: "🔄 रीसेट",
    fert_resultTitle: "आपकी उर्वरक सलाह यहाँ दिखेगी",
    fert_resultDesc: "फसल, मिट्टी का प्रकार और NPK मान दर्ज करें",
    fert_success: "उर्वरक सिफारिश सहेजी गई!",
    fert_error_empty: "कृपया सभी फ़ील्ड भरें।",

    irrig_title: "💧 सिंचाई सलाह",
    irrig_subtitle: "अपनी फसल का प्रकार, मिट्टी की नमी, तापमान और विकास चरण बताएं।",
    irrig_formTitle: "📋 खेत की स्थिति",
    irrig_cropName: "फसल का नाम",
    irrig_growthStage: "विकास चरण",
    irrig_soilMoisture: "मिट्टी की नमी",
    irrig_temperature: "तापमान",
    irrig_selectCrop: "-- फसल चुनें --",
    irrig_selectStage: "-- विकास चरण चुनें --",
    irrig_submit: "💧 सिंचाई योजना पाएं",
    irrig_loading: "गणना हो रही है...",
    irrig_reset: "🔄 रीसेट",
    irrig_resultTitle: "आपकी सिंचाई योजना यहाँ दिखेगी",
    irrig_resultDesc: "अपनी फसल चुनें और खेत की स्थिति दर्ज करें",
    irrig_success: "सिंचाई योजना तैयार और सहेजी गई!",
    irrig_error_empty: "कृपया सभी फ़ील्ड भरें।",
    irrig_tip_moisture: "आपकी मिट्टी की वर्तमान नमी स्तर (0–100%)",
    irrig_tip_temp: "आपके खेत में वर्तमान दिन का तापमान",

    disease_title: "🦠 रोग पहचान",
    disease_subtitle: "अपनी फसल चुनें और लक्षण बताएं। हमारा AI संभावित रोग की पहचान करेगा।",
    disease_formTitle: "📋 समस्या का विवरण दें",
    disease_cropLabel: "प्रभावित फसल",
    disease_selectCrop: "-- प्रभावित फसल चुनें --",
    disease_symptomsLabel: "देखे गए लक्षण",
    disease_symptomsHint: "पौधे पर जो भी लक्षण दिख रहे हैं वे सभी चुनें:",
    disease_customLabel: "अतिरिक्त लक्षण विवरण (वैकल्पिक)",
    disease_customPlaceholder: "जैसे पत्तियाँ भुरभुरी होकर जल्दी गिर रही हैं",
    disease_selectedCount: "लक्षण चुने गए",
    disease_submit: "🔬 रोग पहचानें",
    disease_loading: "पहचान हो रही है...",
    disease_reset: "🔄 रीसेट",
    disease_resultTitle: "रोग पहचान परिणाम यहाँ दिखेगा",
    disease_resultDesc: "अपनी फसल और कम से कम एक लक्षण चुनें",
    disease_success: "रोग पहचाना गया। परिणाम इतिहास में सहेजा गया।",
    disease_supportedTitle: "📋 समर्थित रोग",
    disease_supportedDesc: "हमारा सिस्टम इन रोगों की पहचान कर सकता है:",
    disease_error_noCrop: "कृपया पहले अपनी फसल चुनें।",
    disease_error_noSymptom: "कृपया कम से कम एक लक्षण चुनें या बताएं।",
    sym1: "पीली पत्तियाँ",
    sym2: "पत्तियों पर भूरे धब्बे",
    sym3: "तने का मुरझाना",
    sym4: "पत्तियों पर सफेद पाउडर",
    sym5: "काले घाव",
    sym6: "बौना विकास",
    sym7: "जड़ सड़न",
    sym8: "पत्ती मुड़ना",
    sym9: "फल का रंग बदलना",
    sym10: "समय से पहले फल गिरना",
    sym11: "पानी से भीगे धब्बे",
    sym12: "जंग के नारंगी दाने",

    profile_title: "👨‍🌾 मेरी प्रोफाइल",
    profile_subtitle: "अपनी खाता जानकारी प्रबंधित करें",
    profile_loading: "आपकी प्रोफाइल लोड हो रही है...",
    profile_location: "📍 स्थान",
    profile_member: "📅 सदस्य बने",
    profile_notSet: "सेट नहीं है",
    profile_editTitle: "जानकारी संपादित करें",
    profile_editBtn: "✏️ प्रोफाइल संपादित करें",
    profile_name: "पूरा नाम",
    profile_email: "ईमेल पता",
    profile_emailNote: "पंजीकरण के बाद ईमेल पता नहीं बदला जा सकता।",
    profile_locationLabel: "स्थान / गाँव",
    profile_save: "💾 परिवर्तन सहेजें",
    profile_saving: "सहेजा जा रहा है...",
    profile_cancel: "रद्द करें",
    profile_dangerTitle: "⚠️ खतरनाक क्षेत्र",
    profile_dangerDesc: "खाता हटाना स्थायी है। आपकी सभी सिफारिशें और डेटा हमेशा के लिए हटा दिए जाएंगे।",
    profile_deleteBtn: "🗑️ मेरा खाता हटाएं",
    profile_deleting: "हटाया जा रहा है...",
    profile_success: "प्रोफाइल सफलतापूर्वक अपडेट की गई!",
    profile_error_name: "नाम खाली नहीं हो सकता।",
    profile_confirmDelete: "क्या आप वाकई अपना खाता हटाना चाहते हैं?\n\nआपकी सभी सिफारिशें और डेटा स्थायी रूप से हटा दिए जाएंगे।",

    loading_ai: "AI आपके खेत के डेटा का विश्लेषण कर रहा है...",
    loading_disease: "AI लक्षणों का विश्लेषण कर रहा है...",
    loading_fertilizer: "उर्वरक सिफारिश की गणना हो रही है...",
    loading_irrigation: "आपकी सिंचाई योजना की गणना हो रही है...",
    loading_history: "आपका इतिहास लोड हो रहा है...",
  },

  // ── MARATHI ───────────────────────────────────────────────
  mr: {
    selectLanguage: "भाषा निवडा",
    languageName: "मराठी",
    nav_home: "मुखपृष्ठ",
    nav_dashboard: "डॅशबोर्ड",
    nav_advisories: "सल्ला ▾",
    nav_crop: "🌾 पीक शिफारस",
    nav_fertilizer: "💊 खत",
    nav_irrigation: "💧 सिंचन",
    nav_disease: "🦠 रोग ओळख",
    nav_profile: "माझे प्रोफाइल",
    nav_logout: "लॉग आउट",
    nav_login: "लॉग इन",
    nav_register: "नोंदणी",
    home_badge: "🌿 AI-शक्तीचे शेती",
    home_title1: "स्मार्ट शेती सुरू होते",
    home_title2: "स्मार्ट डेटाने",
    home_desc: "आपल्या वास्तविक शेत परिस्थितीवर आधारित पीक, खत, सिंचन आणि रोग ओळखण्यासाठी AI-आधारित वैयक्तिक शिफारसी मिळवा।",
    home_getStarted: "🌱 मोफत सुरू करा",
    home_login: "🔑 लॉग इन",
    home_dashboard: "🌾 डॅशबोर्डवर जा",
    home_stat1: "पीक मॉडेल अचूकता",
    home_stat2: "समर्थित पिके",
    home_stat3: "AI मॉडेल",
    home_whatWeOffer: "आम्ही काय देतो",
    home_whatDesc: "प्रशिक्षित मशीन लर्निंग मॉडेलद्वारे चार बुद्धिमान सल्ला सेवा",
    home_howItWorks: "हे कसे काम करते",
    home_howDesc: "मातीच्या डेटापासून उपयुक्त शिफारसींपर्यंत चार सोपे टप्पे",
    home_builtWith: "आधुनिक तंत्रज्ञानाने बनवले",
    home_builtDesc: "तीन-स्तरीय पूर्ण-स्टॅक आर्किटेक्चर",
    home_readyTitle: "स्मार्ट शेतीसाठी तयार आहात?",
    home_readyDesc: "आपले मोफत खाते तयार करा आणि काही मिनिटांत पहिली शिफारस मिळवा।",
    home_startNow: "🌱 आता सुरू करा — हे मोफत आहे",
    feat1_title: "पीक शिफारस",
    feat1_desc: "माती NPK मूल्ये, तापमान, आर्द्रता, pH आणि पाऊस दर्ज करा आणि सर्वोत्तम पीक शिफारस मिळवा.",
    feat2_title: "खत सल्ला",
    feat2_desc: "आपल्या पीक निवड आणि मातीच्या पोषक पातळीवर आधारित वैयक्तिक खत शिफारस मिळवा.",
    feat3_title: "सिंचन मार्गदर्शन",
    feat3_desc: "आपल्या पिकाला किती पाण्याची गरज आहे आणि किती वेळा सिंचन करायचे हे जाणून घ्या.",
    feat4_title: "रोग ओळख",
    feat4_desc: "लक्षणे सांगा आणि त्वरित रोग ओळख आणि उपचार मार्गदर्शन मिळवा.",
    step1_title: "शेताचा डेटा द्या",
    step1_desc: "आपली माती मूल्ये आणि स्थानिक हवामान माहिती द्या.",
    step2_title: "AI विश्लेषण",
    step2_desc: "आमचे ML मॉडेल आपल्या डेटाचे रिअल टाइममध्ये विश्लेषण करतात.",
    step3_title: "शिफारस मिळवा",
    step3_desc: "वैयक्तिक, व्यावहारिक कृषी सल्ला मिळवा.",
    step4_title: "इतिहास पहा",
    step4_desc: "सर्व शिफारसी भविष्याच्या संदर्भासाठी जतन केल्या जातात.",
    login_welcome: "पुन्हा स्वागत आहे",
    login_subtitle: "आपल्या स्मार्ट क्रॉप अॅडव्हायजर खात्यात साइन इन करा",
    login_email: "ईमेल पत्ता",
    login_password: "पासवर्ड",
    login_submit: "🔑 साइन इन करा",
    login_loading: "साइन इन होत आहे...",
    login_noAccount: "खाते नाही?",
    login_createOne: "येथे तयार करा",
    login_error_empty: "कृपया ईमेल आणि पासवर्ड दोन्ही भरा.",
    register_title: "खाते तयार करा",
    register_subtitle: "स्मार्ट क्रॉप अॅडव्हायजरमध्ये सामील व्हा",
    register_name: "पूर्ण नाव",
    register_email: "ईमेल पत्ता",
    register_location: "स्थान / गाव",
    register_password: "पासवर्ड",
    register_confirmPassword: "पासवर्ड पुष्टी करा",
    register_submit: "🌱 माझे खाते तयार करा",
    register_loading: "खाते तयार होत आहे...",
    register_haveAccount: "आधीच खाते आहे?",
    register_signIn: "येथे साइन इन करा",
    register_success: "खाते तयार झाले! लॉगिनवर जात आहे...",
    register_error_empty: "सर्व फील्ड आवश्यक आहेत.",
    register_error_password: "पासवर्ड जुळत नाहीत.",
    register_error_short: "पासवर्ड किमान 6 अक्षरांचा असावा.",
    dash_welcome: "पुन्हा स्वागत आहे,",
    dash_subtitle: "आपल्या कृषी सल्ला सारांश आणि अलीकडील क्रियाकलाप येथे आहे.",
    dash_profile: "👨‍🌾 माझे प्रोफाइल",
    dash_totalAdvisories: "एकूण सल्ले",
    dash_cropRec: "पीक शिफारसी",
    dash_fertAdvisory: "खत सल्ले",
    dash_lastDate: "शेवटची सल्ला तारीख",
    dash_quickActions: "जलद क्रिया",
    dash_recentRec: "अलीकडील शिफारसी",
    dash_noHistory: "अजून कोणत्याही शिफारसी नाहीत.",
    dash_noHistoryDesc: "सुरू करण्यासाठी पीक शिफारस वैशिष्ट्य वापरा!",
    dash_getFirst: "पहिली शिफारस मिळवा",
    dash_loading: "आपला इतिहास लोड होत आहे...",
    dash_col_type: "प्रकार",
    dash_col_result: "परिणाम",
    dash_col_confidence: "विश्वास",
    dash_col_date: "तारीख",
    crop_title: "🌾 पीक शिफारस",
    crop_subtitle: "माती आणि हवामान डेटा द्या. आमचे AI मॉडेल सर्वोत्तम पीक सुचवेल.",
    crop_formTitle: "📋 शेताचा डेटा द्या",
    crop_formSubtitle: "सर्व मूल्ये आपल्या सध्याच्या शेत परिस्थितीचे प्रतिबिंब असावीत.",
    crop_nitrogen: "नायट्रोजन (N)",
    crop_phosphorus: "फॉस्फरस (P)",
    crop_potassium: "पोटॅशियम (K)",
    crop_temperature: "तापमान",
    crop_humidity: "आर्द्रता",
    crop_ph: "मातीचा pH",
    crop_rainfall: "पाऊस",
    crop_submit: "🤖 शिफारस मिळवा",
    crop_loading: "विश्लेषण होत आहे...",
    crop_reset: "🔄 रीसेट",
    crop_resultTitle: "आपली शिफारस येथे दिसेल",
    crop_resultDesc: "फॉर्म भरा आणि शिफारस मिळवा बटण दाबा",
    crop_success: "शिफारस तयार झाली आणि जतन केली गेली!",
    crop_error_empty: "कृपया सबमिट करण्यापूर्वी सर्व फील्ड भरा.",
    crop_tip_n: "मातीत उपलब्ध नायट्रोजन. आदर्श: 0–140 mg/kg",
    crop_tip_p: "मातीत उपलब्ध फॉस्फरस. आदर्श: 5–145 mg/kg",
    crop_tip_k: "मातीत उपलब्ध पोटॅशियम. आदर्श: 5–205 mg/kg",
    crop_tip_temp: "सरासरी स्थानिक तापमान. आदर्श: 10–45 °C",
    crop_tip_humidity: "शेतातील सापेक्ष आर्द्रता. श्रेणी: 14–100 %",
    crop_tip_ph: "मातीची आम्लता/क्षारीयता. तटस्थ 7 आहे. श्रेणी: 3.5–10",
    crop_tip_rainfall: "वार्षिक किंवा हंगामी पाऊस. श्रेणी: 20–300 mm",
    card_cropLabel: "पीक शिफारस",
    card_fertLabel: "खत शिफारस",
    card_irrigLabel: "सिंचन सल्ला",
    card_diseaseLabel: "रोग ओळख परिणाम",
    card_confidence: "विश्वास",
    card_alternatives: "पर्याय:",
    card_advisory: "📋 सल्ला नोट",
    card_prevention: "🛡️ प्रतिबंध",
    card_quantity: "प्रमाण:",
    card_frequency: "वारंवारता:",
    card_method: "पद्धत:",
    card_severity: "तीव्रता",
    fert_title: "💊 खत शिफारस",
    fert_subtitle: "आपले पीक आणि मातीचा प्रकार निवडा, NPK पातळी द्या.",
    fert_formTitle: "📋 तपशील द्या",
    fert_cropName: "पिकाचे नाव",
    fert_soilType: "मातीचा प्रकार",
    fert_selectCrop: "-- आपले पीक निवडा --",
    fert_selectSoil: "-- मातीचा प्रकार निवडा --",
    fert_nitrogen: "नायट्रोजन (N)",
    fert_phosphorus: "फॉस्फरस (P)",
    fert_potassium: "पोटॅशियम (K)",
    fert_submit: "💊 खत सल्ला मिळवा",
    fert_loading: "विश्लेषण होत आहे...",
    fert_reset: "🔄 रीसेट",
    fert_resultTitle: "आपला खत सल्ला येथे दिसेल",
    fert_resultDesc: "पीक, मातीचा प्रकार आणि NPK मूल्ये द्या",
    fert_success: "खत शिफारस जतन केली!",
    fert_error_empty: "कृपया सर्व फील्ड भरा.",
    irrig_title: "💧 सिंचन सल्ला",
    irrig_subtitle: "आपल्या पिकाचा प्रकार, मातीची ओलावा, तापमान आणि वाढीचा टप्पा सांगा.",
    irrig_formTitle: "📋 शेत परिस्थिती",
    irrig_cropName: "पिकाचे नाव",
    irrig_growthStage: "वाढीचा टप्पा",
    irrig_soilMoisture: "मातीची ओलावा",
    irrig_temperature: "तापमान",
    irrig_selectCrop: "-- पीक निवडा --",
    irrig_selectStage: "-- वाढीचा टप्पा निवडा --",
    irrig_submit: "💧 सिंचन योजना मिळवा",
    irrig_loading: "गणना होत आहे...",
    irrig_reset: "🔄 रीसेट",
    irrig_resultTitle: "आपली सिंचन योजना येथे दिसेल",
    irrig_resultDesc: "आपले पीक निवडा आणि शेत परिस्थिती द्या",
    irrig_success: "सिंचन योजना तयार आणि जतन केली!",
    irrig_error_empty: "कृपया सर्व फील्ड भरा.",
    irrig_tip_moisture: "आपल्या मातीची सध्याची ओलावा पातळी (0–100%)",
    irrig_tip_temp: "आपल्या शेतातील सध्याचे दिवसाचे तापमान",
    disease_title: "🦠 रोग ओळख",
    disease_subtitle: "आपले पीक निवडा आणि लक्षणे सांगा. आमचे AI संभाव्य रोग ओळखेल.",
    disease_formTitle: "📋 समस्या सांगा",
    disease_cropLabel: "प्रभावित पीक",
    disease_selectCrop: "-- प्रभावित पीक निवडा --",
    disease_symptomsLabel: "दिसणारी लक्षणे",
    disease_symptomsHint: "झाडावर जी लक्षणे दिसत आहेत ती सर्व निवडा:",
    disease_customLabel: "अतिरिक्त लक्षण वर्णन (पर्यायी)",
    disease_customPlaceholder: "उदा. पाने ठिसूळ होऊन लवकर गळत आहेत",
    disease_selectedCount: "लक्षणे निवडली",
    disease_submit: "🔬 रोग ओळखा",
    disease_loading: "ओळख होत आहे...",
    disease_reset: "🔄 रीसेट",
    disease_resultTitle: "रोग ओळख परिणाम येथे दिसेल",
    disease_resultDesc: "आपले पीक आणि किमान एक लक्षण निवडा",
    disease_success: "रोग ओळखला. परिणाम इतिहासात जतन केला.",
    disease_supportedTitle: "📋 समर्थित रोग",
    disease_supportedDesc: "आमची प्रणाली हे रोग ओळखू शकते:",
    disease_error_noCrop: "कृपया आधी आपले पीक निवडा.",
    disease_error_noSymptom: "कृपया किमान एक लक्षण निवडा किंवा सांगा.",
    sym1: "पिवळी पाने",
    sym2: "पानांवर तपकिरी डाग",
    sym3: "खोड कोमेजणे",
    sym4: "पानांवर पांढरी पावडर",
    sym5: "काळे व्रण",
    sym6: "खुरटी वाढ",
    sym7: "मूळ कुजणे",
    sym8: "पान वळणे",
    sym9: "फळाचा रंग बदलणे",
    sym10: "वेळेआधी फळ गळणे",
    sym11: "पाण्याने भिजलेले डाग",
    sym12: "गंजाचे नारंगी ठिपके",
    profile_title: "👨‍🌾 माझे प्रोफाइल",
    profile_subtitle: "आपली खाते माहिती व्यवस्थापित करा",
    profile_loading: "आपले प्रोफाइल लोड होत आहे...",
    profile_location: "📍 स्थान",
    profile_member: "📅 सदस्य झाले",
    profile_notSet: "सेट नाही",
    profile_editTitle: "माहिती संपादित करा",
    profile_editBtn: "✏️ प्रोफाइल संपादित करा",
    profile_name: "पूर्ण नाव",
    profile_email: "ईमेल पत्ता",
    profile_emailNote: "नोंदणीनंतर ईमेल पत्ता बदलता येत नाही.",
    profile_locationLabel: "स्थान / गाव",
    profile_save: "💾 बदल जतन करा",
    profile_saving: "जतन होत आहे...",
    profile_cancel: "रद्द करा",
    profile_dangerTitle: "⚠️ धोकादायक क्षेत्र",
    profile_dangerDesc: "खाते हटवणे कायमचे आहे. आपल्या सर्व शिफारसी आणि डेटा कायमचे हटवले जातील.",
    profile_deleteBtn: "🗑️ माझे खाते हटवा",
    profile_deleting: "हटवले जात आहे...",
    profile_success: "प्रोफाइल यशस्वीरित्या अपडेट केले!",
    profile_error_name: "नाव रिकामे असू शकत नाही.",
    profile_confirmDelete: "आपण खरोखर आपले खाते हटवू इच्छिता?\n\nआपल्या सर्व शिफारसी आणि डेटा कायमचे हटवले जातील.",
    loading_ai: "AI आपल्या शेताच्या डेटाचे विश्लेषण करत आहे...",
    loading_disease: "AI लक्षणांचे विश्लेषण करत आहे...",
    loading_fertilizer: "खत शिफारसची गणना होत आहे...",
    loading_irrigation: "आपल्या सिंचन योजनेची गणना होत आहे...",
    loading_history: "आपला इतिहास लोड होत आहे...",
  },

  // ── PUNJABI ───────────────────────────────────────────────
  pa: {
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    languageName: "ਪੰਜਾਬੀ",
    nav_home: "ਹੋਮ",
    nav_dashboard: "ਡੈਸ਼ਬੋਰਡ",
    nav_advisories: "ਸਲਾਹ ▾",
    nav_crop: "🌾 ਫਸਲ ਸਿਫਾਰਸ਼",
    nav_fertilizer: "💊 ਖਾਦ",
    nav_irrigation: "💧 ਸਿੰਚਾਈ",
    nav_disease: "🦠 ਬਿਮਾਰੀ ਪਛਾਣ",
    nav_profile: "ਮੇਰਾ ਪ੍ਰੋਫਾਈਲ",
    nav_logout: "ਲੌਗ ਆਉਟ",
    nav_login: "ਲੌਗ ਇਨ",
    nav_register: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    home_badge: "🌿 AI-ਸੰਚਾਲਿਤ ਖੇਤੀ",
    home_title1: "ਸਮਾਰਟ ਖੇਤੀ ਸ਼ੁਰੂ ਹੁੰਦੀ ਹੈ",
    home_title2: "ਸਮਾਰਟ ਡੇਟਾ ਨਾਲ",
    home_desc: "ਆਪਣੀ ਅਸਲ ਖੇਤ ਸਥਿਤੀ ਦੇ ਆਧਾਰ 'ਤੇ ਫਸਲ, ਖਾਦ, ਸਿੰਚਾਈ ਅਤੇ ਬਿਮਾਰੀ ਪਛਾਣ ਲਈ AI-ਅਧਾਰਿਤ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ।",
    home_getStarted: "🌱 ਮੁਫਤ ਸ਼ੁਰੂ ਕਰੋ",
    home_login: "🔑 ਲੌਗ ਇਨ",
    home_dashboard: "🌾 ਡੈਸ਼ਬੋਰਡ 'ਤੇ ਜਾਓ",
    home_stat1: "ਫਸਲ ਮਾਡਲ ਸ਼ੁੱਧਤਾ",
    home_stat2: "ਸਮਰਥਿਤ ਫਸਲਾਂ",
    home_stat3: "AI ਮਾਡਲ",
    home_whatWeOffer: "ਅਸੀਂ ਕੀ ਪੇਸ਼ ਕਰਦੇ ਹਾਂ",
    home_whatDesc: "ਸਿੱਖੇ ਹੋਏ ਮਸ਼ੀਨ ਲਰਨਿੰਗ ਮਾਡਲਾਂ ਦੁਆਰਾ ਚਾਰ ਬੁੱਧੀਮਾਨ ਸਲਾਹ ਸੇਵਾਵਾਂ",
    home_howItWorks: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
    home_howDesc: "ਮਿੱਟੀ ਦੇ ਡੇਟਾ ਤੋਂ ਕਾਰਜਯੋਗ ਸਿਫਾਰਸ਼ਾਂ ਤੱਕ ਚਾਰ ਸਧਾਰਨ ਕਦਮ",
    home_builtWith: "ਆਧੁਨਿਕ ਤਕਨਾਲੋਜੀ ਨਾਲ ਬਣਾਇਆ",
    home_builtDesc: "ਤਿੰਨ-ਪੱਧਰੀ ਪੂਰਾ-ਸਟੈਕ ਆਰਕੀਟੈਕਚਰ",
    home_readyTitle: "ਸਮਾਰਟ ਖੇਤੀ ਲਈ ਤਿਆਰ ਹੋ?",
    home_readyDesc: "ਆਪਣਾ ਮੁਫਤ ਖਾਤਾ ਬਣਾਓ ਅਤੇ ਮਿੰਟਾਂ ਵਿੱਚ ਪਹਿਲੀ ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ।",
    home_startNow: "🌱 ਹੁਣੇ ਸ਼ੁਰੂ ਕਰੋ — ਇਹ ਮੁਫਤ ਹੈ",
    feat1_title: "ਫਸਲ ਸਿਫਾਰਸ਼",
    feat1_desc: "ਮਿੱਟੀ NPK ਮੁੱਲ, ਤਾਪਮਾਨ, ਨਮੀ, pH ਅਤੇ ਵਰਖਾ ਦਰਜ ਕਰੋ।",
    feat2_title: "ਖਾਦ ਸਲਾਹ",
    feat2_desc: "ਆਪਣੀ ਫਸਲ ਅਤੇ ਮਿੱਟੀ ਦੇ ਆਧਾਰ 'ਤੇ ਖਾਦ ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ।",
    feat3_title: "ਸਿੰਚਾਈ ਮਾਰਗਦਰਸ਼ਨ",
    feat3_desc: "ਜਾਣੋ ਕਿ ਤੁਹਾਡੀ ਫਸਲ ਨੂੰ ਕਿੰਨੇ ਪਾਣੀ ਦੀ ਲੋੜ ਹੈ।",
    feat4_title: "ਬਿਮਾਰੀ ਪਛਾਣ",
    feat4_desc: "ਲੱਛਣ ਦੱਸੋ ਅਤੇ ਬਿਮਾਰੀ ਪਛਾਣ ਅਤੇ ਇਲਾਜ ਮਾਰਗਦਰਸ਼ਨ ਪ੍ਰਾਪਤ ਕਰੋ।",
    step1_title: "ਖੇਤ ਦਾ ਡੇਟਾ ਦਾਖਲ ਕਰੋ",
    step1_desc: "ਆਪਣੀ ਮਿੱਟੀ ਅਤੇ ਸਥਾਨਕ ਮੌਸਮ ਦੀ ਜਾਣਕਾਰੀ ਦਾਖਲ ਕਰੋ।",
    step2_title: "AI ਵਿਸ਼ਲੇਸ਼ਣ",
    step2_desc: "ਸਾਡੇ ML ਮਾਡਲ ਤੁਹਾਡੇ ਡੇਟਾ ਦਾ ਅਸਲ ਸਮੇਂ ਵਿੱਚ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਦੇ ਹਨ।",
    step3_title: "ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ",
    step3_desc: "ਵਿਅਕਤੀਗਤ, ਕਾਰਜਯੋਗ ਖੇਤੀ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ।",
    step4_title: "ਇਤਿਹਾਸ ਟਰੈਕ ਕਰੋ",
    step4_desc: "ਸਾਰੀਆਂ ਸਿਫਾਰਸ਼ਾਂ ਭਵਿੱਖ ਦੇ ਸੰਦਰਭ ਲਈ ਸੁਰੱਖਿਅਤ ਕੀਤੀਆਂ ਜਾਂਦੀਆਂ ਹਨ।",
    login_welcome: "ਵਾਪਸ ਸੁਆਗਤ ਹੈ",
    login_subtitle: "ਆਪਣੇ ਸਮਾਰਟ ਕ੍ਰੌਪ ਅਡਵਾਈਜ਼ਰ ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ",
    login_email: "ਈਮੇਲ ਪਤਾ",
    login_password: "ਪਾਸਵਰਡ",
    login_submit: "🔑 ਸਾਈਨ ਇਨ ਕਰੋ",
    login_loading: "ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...",
    login_noAccount: "ਖਾਤਾ ਨਹੀਂ ਹੈ?",
    login_createOne: "ਇੱਥੇ ਬਣਾਓ",
    login_error_empty: "ਕਿਰਪਾ ਕਰਕੇ ਈਮੇਲ ਅਤੇ ਪਾਸਵਰਡ ਦੋਵੇਂ ਭਰੋ।",
    register_title: "ਖਾਤਾ ਬਣਾਓ",
    register_subtitle: "ਸਮਾਰਟ ਕ੍ਰੌਪ ਅਡਵਾਈਜ਼ਰ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ",
    register_name: "ਪੂਰਾ ਨਾਮ",
    register_email: "ਈਮੇਲ ਪਤਾ",
    register_location: "ਸਥਾਨ / ਪਿੰਡ",
    register_password: "ਪਾਸਵਰਡ",
    register_confirmPassword: "ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    register_submit: "🌱 ਮੇਰਾ ਖਾਤਾ ਬਣਾਓ",
    register_loading: "ਖਾਤਾ ਬਣ ਰਿਹਾ ਹੈ...",
    register_haveAccount: "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?",
    register_signIn: "ਇੱਥੇ ਸਾਈਨ ਇਨ ਕਰੋ",
    register_success: "ਖਾਤਾ ਬਣਾਇਆ ਗਿਆ! ਲੌਗਇਨ ਵੱਲ ਜਾ ਰਹੇ ਹਾਂ...",
    register_error_empty: "ਸਾਰੇ ਫੀਲਡ ਲਾਜ਼ਮੀ ਹਨ।",
    register_error_password: "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ।",
    register_error_short: "ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।",
    dash_welcome: "ਵਾਪਸ ਸੁਆਗਤ ਹੈ,",
    dash_subtitle: "ਇੱਥੇ ਤੁਹਾਡਾ ਖੇਤੀ ਸਲਾਹ ਸਾਰਾਂਸ਼ ਅਤੇ ਹਾਲੀਆ ਗਤੀਵਿਧੀ ਹੈ।",
    dash_profile: "👨‍🌾 ਮੇਰਾ ਪ੍ਰੋਫਾਈਲ",
    dash_totalAdvisories: "ਕੁੱਲ ਸਲਾਹਾਂ",
    dash_cropRec: "ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ",
    dash_fertAdvisory: "ਖਾਦ ਸਲਾਹਾਂ",
    dash_lastDate: "ਆਖਰੀ ਸਲਾਹ ਮਿਤੀ",
    dash_quickActions: "ਤੇਜ਼ ਕਾਰਵਾਈਆਂ",
    dash_recentRec: "ਹਾਲੀਆ ਸਿਫਾਰਸ਼ਾਂ",
    dash_noHistory: "ਅਜੇ ਕੋਈ ਸਿਫਾਰਸ਼ਾਂ ਨਹੀਂ।",
    dash_noHistoryDesc: "ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਫਸਲ ਸਿਫਾਰਸ਼ ਵਿਸ਼ੇਸ਼ਤਾ ਅਜ਼ਮਾਓ!",
    dash_getFirst: "ਪਹਿਲੀ ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ",
    dash_loading: "ਤੁਹਾਡਾ ਇਤਿਹਾਸ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    dash_col_type: "ਕਿਸਮ",
    dash_col_result: "ਨਤੀਜਾ",
    dash_col_confidence: "ਭਰੋਸਾ",
    dash_col_date: "ਮਿਤੀ",
    crop_title: "🌾 ਫਸਲ ਸਿਫਾਰਸ਼",
    crop_subtitle: "ਆਪਣੀ ਮਿੱਟੀ ਅਤੇ ਮੌਸਮ ਡੇਟਾ ਦਾਖਲ ਕਰੋ। ਸਾਡਾ AI ਮਾਡਲ ਸਭ ਤੋਂ ਵਧੀਆ ਫਸਲ ਦੀ ਸਿਫਾਰਸ਼ ਕਰੇਗਾ।",
    crop_formTitle: "📋 ਖੇਤ ਡੇਟਾ ਦਾਖਲ ਕਰੋ",
    crop_formSubtitle: "ਸਾਰੇ ਮੁੱਲ ਤੁਹਾਡੀਆਂ ਮੌਜੂਦਾ ਖੇਤ ਹਾਲਤਾਂ ਨੂੰ ਦਰਸਾਉਣੇ ਚਾਹੀਦੇ ਹਨ।",
    crop_nitrogen: "ਨਾਈਟ੍ਰੋਜਨ (N)",
    crop_phosphorus: "ਫਾਸਫੋਰਸ (P)",
    crop_potassium: "ਪੋਟਾਸ਼ੀਅਮ (K)",
    crop_temperature: "ਤਾਪਮਾਨ",
    crop_humidity: "ਨਮੀ",
    crop_ph: "ਮਿੱਟੀ ਦਾ pH",
    crop_rainfall: "ਵਰਖਾ",
    crop_submit: "🤖 ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ",
    crop_loading: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    crop_reset: "🔄 ਰੀਸੈਟ",
    crop_resultTitle: "ਤੁਹਾਡੀ ਸਿਫਾਰਸ਼ ਇੱਥੇ ਦਿਖੇਗੀ",
    crop_resultDesc: "ਫਾਰਮ ਭਰੋ ਅਤੇ ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ ਬਟਨ ਦਬਾਓ",
    crop_success: "ਸਿਫਾਰਸ਼ ਤਿਆਰ ਕੀਤੀ ਅਤੇ ਸੁਰੱਖਿਅਤ ਕੀਤੀ!",
    crop_error_empty: "ਕਿਰਪਾ ਕਰਕੇ ਸਬਮਿਟ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਸਾਰੇ ਫੀਲਡ ਭਰੋ।",
    crop_tip_n: "ਮਿੱਟੀ ਵਿੱਚ ਉਪਲਬਧ ਨਾਈਟ੍ਰੋਜਨ। ਆਦਰਸ਼: 0–140 mg/kg",
    crop_tip_p: "ਮਿੱਟੀ ਵਿੱਚ ਉਪਲਬਧ ਫਾਸਫੋਰਸ। ਆਦਰਸ਼: 5–145 mg/kg",
    crop_tip_k: "ਮਿੱਟੀ ਵਿੱਚ ਉਪਲਬਧ ਪੋਟਾਸ਼ੀਅਮ। ਆਦਰਸ਼: 5–205 mg/kg",
    crop_tip_temp: "ਔਸਤ ਸਥਾਨਕ ਤਾਪਮਾਨ। ਆਦਰਸ਼: 10–45 °C",
    crop_tip_humidity: "ਖੇਤ ਵਿੱਚ ਸਾਪੇਖ ਨਮੀ। ਸੀਮਾ: 14–100 %",
    crop_tip_ph: "ਮਿੱਟੀ ਦੀ ਤੇਜ਼ਾਬੀਅਤ। ਨਿਰਪੱਖ 7 ਹੈ। ਸੀਮਾ: 3.5–10",
    crop_tip_rainfall: "ਸਾਲਾਨਾ ਜਾਂ ਮੌਸਮੀ ਵਰਖਾ। ਸੀਮਾ: 20–300 mm",
    card_cropLabel: "ਫਸਲ ਸਿਫਾਰਸ਼",
    card_fertLabel: "ਖਾਦ ਸਿਫਾਰਸ਼",
    card_irrigLabel: "ਸਿੰਚਾਈ ਸਲਾਹ",
    card_diseaseLabel: "ਬਿਮਾਰੀ ਪਛਾਣ ਨਤੀਜਾ",
    card_confidence: "ਭਰੋਸਾ",
    card_alternatives: "ਬਦਲ:",
    card_advisory: "📋 ਸਲਾਹ ਨੋਟ",
    card_prevention: "🛡️ ਰੋਕਥਾਮ",
    card_quantity: "ਮਾਤਰਾ:",
    card_frequency: "ਬਾਰੰਬਾਰਤਾ:",
    card_method: "ਵਿਧੀ:",
    card_severity: "ਗੰਭੀਰਤਾ",
    fert_title: "💊 ਖਾਦ ਸਿਫਾਰਸ਼",
    fert_subtitle: "ਆਪਣੀ ਫਸਲ ਅਤੇ ਮਿੱਟੀ ਦੀ ਕਿਸਮ ਚੁਣੋ, NPK ਪੱਧਰ ਦਾਖਲ ਕਰੋ।",
    fert_formTitle: "📋 ਵੇਰਵੇ ਦਾਖਲ ਕਰੋ",
    fert_cropName: "ਫਸਲ ਦਾ ਨਾਮ",
    fert_soilType: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
    fert_selectCrop: "-- ਆਪਣੀ ਫਸਲ ਚੁਣੋ --",
    fert_selectSoil: "-- ਮਿੱਟੀ ਦੀ ਕਿਸਮ ਚੁਣੋ --",
    fert_nitrogen: "ਨਾਈਟ੍ਰੋਜਨ (N)",
    fert_phosphorus: "ਫਾਸਫੋਰਸ (P)",
    fert_potassium: "ਪੋਟਾਸ਼ੀਅਮ (K)",
    fert_submit: "💊 ਖਾਦ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ",
    fert_loading: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    fert_reset: "🔄 ਰੀਸੈਟ",
    fert_resultTitle: "ਤੁਹਾਡੀ ਖਾਦ ਸਲਾਹ ਇੱਥੇ ਦਿਖੇਗੀ",
    fert_resultDesc: "ਫਸਲ, ਮਿੱਟੀ ਦੀ ਕਿਸਮ ਅਤੇ NPK ਮੁੱਲ ਦਾਖਲ ਕਰੋ",
    fert_success: "ਖਾਦ ਸਿਫਾਰਸ਼ ਸੁਰੱਖਿਅਤ ਕੀਤੀ!",
    fert_error_empty: "ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਫੀਲਡ ਭਰੋ।",
    irrig_title: "💧 ਸਿੰਚਾਈ ਸਲਾਹ",
    irrig_subtitle: "ਆਪਣੀ ਫਸਲ ਦੀ ਕਿਸਮ, ਮਿੱਟੀ ਦੀ ਨਮੀ, ਤਾਪਮਾਨ ਅਤੇ ਵਿਕਾਸ ਦਾ ਪੜਾਅ ਦੱਸੋ।",
    irrig_formTitle: "📋 ਖੇਤ ਦੀਆਂ ਹਾਲਤਾਂ",
    irrig_cropName: "ਫਸਲ ਦਾ ਨਾਮ",
    irrig_growthStage: "ਵਿਕਾਸ ਦਾ ਪੜਾਅ",
    irrig_soilMoisture: "ਮਿੱਟੀ ਦੀ ਨਮੀ",
    irrig_temperature: "ਤਾਪਮਾਨ",
    irrig_selectCrop: "-- ਫਸਲ ਚੁਣੋ --",
    irrig_selectStage: "-- ਵਿਕਾਸ ਦਾ ਪੜਾਅ ਚੁਣੋ --",
    irrig_submit: "💧 ਸਿੰਚਾਈ ਯੋਜਨਾ ਪ੍ਰਾਪਤ ਕਰੋ",
    irrig_loading: "ਗਣਨਾ ਹੋ ਰਹੀ ਹੈ...",
    irrig_reset: "🔄 ਰੀਸੈਟ",
    irrig_resultTitle: "ਤੁਹਾਡੀ ਸਿੰਚਾਈ ਯੋਜਨਾ ਇੱਥੇ ਦਿਖੇਗੀ",
    irrig_resultDesc: "ਆਪਣੀ ਫਸਲ ਚੁਣੋ ਅਤੇ ਖੇਤ ਦੀਆਂ ਹਾਲਤਾਂ ਦਾਖਲ ਕਰੋ",
    irrig_success: "ਸਿੰਚਾਈ ਯੋਜਨਾ ਤਿਆਰ ਅਤੇ ਸੁਰੱਖਿਅਤ ਕੀਤੀ!",
    irrig_error_empty: "ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਫੀਲਡ ਭਰੋ।",
    irrig_tip_moisture: "ਤੁਹਾਡੀ ਮਿੱਟੀ ਦੀ ਮੌਜੂਦਾ ਨਮੀ ਦਾ ਪੱਧਰ (0–100%)",
    irrig_tip_temp: "ਤੁਹਾਡੇ ਖੇਤ ਵਿੱਚ ਮੌਜੂਦਾ ਦਿਨ ਦਾ ਤਾਪਮਾਨ",
    disease_title: "🦠 ਬਿਮਾਰੀ ਪਛਾਣ",
    disease_subtitle: "ਆਪਣੀ ਫਸਲ ਚੁਣੋ ਅਤੇ ਲੱਛਣ ਦੱਸੋ। ਸਾਡਾ AI ਸੰਭਾਵਿਤ ਬਿਮਾਰੀ ਦੀ ਪਛਾਣ ਕਰੇਗਾ।",
    disease_formTitle: "📋 ਸਮੱਸਿਆ ਦਾ ਵੇਰਵਾ ਦਿਓ",
    disease_cropLabel: "ਪ੍ਰਭਾਵਿਤ ਫਸਲ",
    disease_selectCrop: "-- ਪ੍ਰਭਾਵਿਤ ਫਸਲ ਚੁਣੋ --",
    disease_symptomsLabel: "ਦੇਖੇ ਗਏ ਲੱਛਣ",
    disease_symptomsHint: "ਪੌਦੇ 'ਤੇ ਜੋ ਲੱਛਣ ਦਿਖ ਰਹੇ ਹਨ ਉਹ ਸਾਰੇ ਚੁਣੋ:",
    disease_customLabel: "ਵਾਧੂ ਲੱਛਣ ਵੇਰਵਾ (ਵਿਕਲਪਿਕ)",
    disease_customPlaceholder: "ਜਿਵੇਂ ਪੱਤੇ ਭੁਰਭੁਰੇ ਹੋ ਕੇ ਜਲਦੀ ਡਿੱਗ ਰਹੇ ਹਨ",
    disease_selectedCount: "ਲੱਛਣ ਚੁਣੇ ਗਏ",
    disease_submit: "🔬 ਬਿਮਾਰੀ ਦੀ ਪਛਾਣ ਕਰੋ",
    disease_loading: "ਪਛਾਣ ਹੋ ਰਹੀ ਹੈ...",
    disease_reset: "🔄 ਰੀਸੈਟ",
    disease_resultTitle: "ਬਿਮਾਰੀ ਪਛਾਣ ਨਤੀਜਾ ਇੱਥੇ ਦਿਖੇਗਾ",
    disease_resultDesc: "ਆਪਣੀ ਫਸਲ ਅਤੇ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਲੱਛਣ ਚੁਣੋ",
    disease_success: "ਬਿਮਾਰੀ ਦੀ ਪਛਾਣ ਹੋਈ। ਨਤੀਜਾ ਇਤਿਹਾਸ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਕੀਤਾ।",
    disease_supportedTitle: "📋 ਸਮਰਥਿਤ ਬਿਮਾਰੀਆਂ",
    disease_supportedDesc: "ਸਾਡਾ ਸਿਸਟਮ ਇਹ ਬਿਮਾਰੀਆਂ ਪਛਾਣ ਸਕਦਾ ਹੈ:",
    disease_error_noCrop: "ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਆਪਣੀ ਫਸਲ ਚੁਣੋ।",
    disease_error_noSymptom: "ਕਿਰਪਾ ਕਰਕੇ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਲੱਛਣ ਚੁਣੋ ਜਾਂ ਦੱਸੋ।",
    sym1: "ਪੀਲੇ ਪੱਤੇ",
    sym2: "ਪੱਤਿਆਂ 'ਤੇ ਭੂਰੇ ਧੱਬੇ",
    sym3: "ਤਣੇ ਦਾ ਮੁਰਝਾਉਣਾ",
    sym4: "ਪੱਤਿਆਂ 'ਤੇ ਚਿੱਟਾ ਪਾਊਡਰ",
    sym5: "ਕਾਲੇ ਜ਼ਖਮ",
    sym6: "ਬੌਣਾ ਵਿਕਾਸ",
    sym7: "ਜੜ੍ਹਾਂ ਦਾ ਸੜਨਾ",
    sym8: "ਪੱਤਾ ਮੁੜਨਾ",
    sym9: "ਫਲ ਦਾ ਰੰਗ ਬਦਲਣਾ",
    sym10: "ਸਮੇਂ ਤੋਂ ਪਹਿਲਾਂ ਫਲ ਡਿੱਗਣਾ",
    sym11: "ਪਾਣੀ ਭਿੱਜੇ ਧੱਬੇ",
    sym12: "ਜੰਗ ਦੇ ਸੰਤਰੀ ਦਾਣੇ",
    profile_title: "👨‍🌾 ਮੇਰਾ ਪ੍ਰੋਫਾਈਲ",
    profile_subtitle: "ਆਪਣੀ ਖਾਤਾ ਜਾਣਕਾਰੀ ਪ੍ਰਬੰਧਿਤ ਕਰੋ",
    profile_loading: "ਤੁਹਾਡਾ ਪ੍ਰੋਫਾਈਲ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    profile_location: "📍 ਸਥਾਨ",
    profile_member: "📅 ਮੈਂਬਰ ਬਣੇ",
    profile_notSet: "ਸੈੱਟ ਨਹੀਂ",
    profile_editTitle: "ਜਾਣਕਾਰੀ ਸੰਪਾਦਿਤ ਕਰੋ",
    profile_editBtn: "✏️ ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਿਤ ਕਰੋ",
    profile_name: "ਪੂਰਾ ਨਾਮ",
    profile_email: "ਈਮੇਲ ਪਤਾ",
    profile_emailNote: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਤੋਂ ਬਾਅਦ ਈਮੇਲ ਪਤਾ ਨਹੀਂ ਬਦਲਿਆ ਜਾ ਸਕਦਾ।",
    profile_locationLabel: "ਸਥਾਨ / ਪਿੰਡ",
    profile_save: "💾 ਬਦਲਾਅ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    profile_saving: "ਸੁਰੱਖਿਅਤ ਹੋ ਰਿਹਾ ਹੈ...",
    profile_cancel: "ਰੱਦ ਕਰੋ",
    profile_dangerTitle: "⚠️ ਖਤਰਨਾਕ ਖੇਤਰ",
    profile_dangerDesc: "ਖਾਤਾ ਹਟਾਉਣਾ ਸਥਾਈ ਹੈ। ਤੁਹਾਡੀਆਂ ਸਾਰੀਆਂ ਸਿਫਾਰਸ਼ਾਂ ਅਤੇ ਡੇਟਾ ਸਥਾਈ ਤੌਰ 'ਤੇ ਹਟਾਏ ਜਾਣਗੇ।",
    profile_deleteBtn: "🗑️ ਮੇਰਾ ਖਾਤਾ ਹਟਾਓ",
    profile_deleting: "ਹਟਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...",
    profile_success: "ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅਪਡੇਟ ਕੀਤਾ!",
    profile_error_name: "ਨਾਮ ਖਾਲੀ ਨਹੀਂ ਹੋ ਸਕਦਾ।",
    profile_confirmDelete: "ਕੀ ਤੁਸੀਂ ਸੱਚਮੁੱਚ ਆਪਣਾ ਖਾਤਾ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    loading_ai: "AI ਤੁਹਾਡੇ ਖੇਤ ਡੇਟਾ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ...",
    loading_disease: "AI ਲੱਛਣਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ...",
    loading_fertilizer: "ਖਾਦ ਸਿਫਾਰਸ਼ ਦੀ ਗਣਨਾ ਹੋ ਰਹੀ ਹੈ...",
    loading_irrigation: "ਤੁਹਾਡੀ ਸਿੰਚਾਈ ਯੋਜਨਾ ਦੀ ਗਣਨਾ ਹੋ ਰਹੀ ਹੈ...",
    loading_history: "ਤੁਹਾਡਾ ਇਤਿਹਾਸ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
  },
};

// Create the context
const LanguageContext = createContext(null);

// ── LanguageProvider ─────────────────────────────────────────
export function LanguageProvider({ children }) {
  // Read saved language from localStorage or default to English
  const [language, setLanguage] = useState(
    () => localStorage.getItem("sca_language") || "en"
  );

  // Change language and save to localStorage
  const changeLanguage = (langCode) => {
    setLanguage(langCode);
    localStorage.setItem("sca_language", langCode);
  };

  // Toggle language between English and Hindi
  const toggleLanguage = () => {
    const nextLang = language === "en" ? "hi" : "en";
    setLanguage(nextLang);
    localStorage.setItem("sca_language", nextLang);
  };

  // t() — Translation function/object hybrid to support both flat key and nested object usage
  const t = (key) => {
    return translations[language]?.[key] || translations["en"][key] || key;
  };

  // Attach nested translation properties to the function
  const currentNested = customTranslations[language] || customTranslations["en"];
  Object.assign(t, currentNested);

  const value = {
    language,       // Current language code e.g. "hi"
    lang: language, // Alias for Navbar.jsx
    changeLanguage, // Function to change language
    toggleLanguage, // Function to toggle language for Navbar.jsx
    t,              // Translation function/object
    translations: customTranslations, // Hierarchical translations
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

// Custom hook
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside <LanguageProvider>");
  }
  return context;
}

export default LanguageContext;