// ============================================================
//  FILE LOCATION:
//  src/main/java/com/smartcropadvisor/backend/dto/AuthResponse.java
//
//  WHAT THIS DTO IS FOR:
//  This is an OUTGOING DTO — it carries data FROM our backend TO frontend.
//  Returned after successful login OR registration.
//
//  Frontend receives this JSON:
//  {
//    "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcnBpdEBnbWFpbC5jb20...",
//    "userId": 1,
//    "name": "Arpit Umrao",
//    "email": "arpit@gmail.com"
//  }
//
//  Frontend (Anubhav) stores the token in localStorage and sends it
//  with every future request in the Authorization header:
//  Authorization: Bearer eyJhbGciOiJIUzI1NiJ9...
//
//  Our JwtAuthFilter (Phase 5) reads this header on every request
//  and validates the token to authenticate the user.
// ============================================================

package com.smartcropadvisor.backend.dto;

public record AuthResponse(

        // ── token ─────────────────────────────────────────────
        // The JWT token generated by JwtUtil.generateToken(user).
        // Frontend stores this and sends it with every API request.
        // Expires after 24 hours (jwt.expiration in application.properties).
        String token,

        // ── userId ────────────────────────────────────────────
        // The database ID of the logged-in user.
        // Frontend uses this to call endpoints like:
        //   GET /api/v1/recommend/history/{userId}
        //   GET /api/v1/user/profile/{userId}
        Long userId,

        // ── name ──────────────────────────────────────────────
        // Farmer's name — frontend shows this in the navbar:
        // "Welcome, Arpit Umrao 👋"
        String name,

        // ── email ─────────────────────────────────────────────
        // Farmer's email — frontend shows in profile/settings page.
        String email

) {}